version: '3.8'

services:
  app:
    build: .
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: pgdb
    volumes:
      - pgdb:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdb:
    external: false
